# https://docs.docker.com/compose/compose-file
version: '3.8'

x-logopts:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields 
    &default-logopts  # https://docs.docker.com/compose/compose-file/compose-file-v3/#logging 
    options:
        max-size: "12m"
        max-file: "5"
    driver: json-file

volumes:  
    pg1_data:
        external: true
    pg2_data:
        external: true
    pg1_arch:
        external: true
    pg2_arch:
        external: true
    pgha_etc:
        external: true
    dbp1_data:
        external: true
    

networks:
    pvt1:
        driver: overlay
        # ipam:
        #     driver: default
        #     config:
        #         - subnet: "10.0.120.0/24"
        #         #- gateway: "10.0.120.1"
        external: true

x-svc: &default-svc
        image: ${PGHA_IMAGE}
        user: "postgres"
        networks:
            pvt1:
        ports:
            - 5432
        # Starting the server : https://www.postgresql.org/docs/current/server-start.html 
        # command: ["postgres", "-c", "config_file=${PATH_ABS_CTNR_PGHOME}/pgha/config/${PG_CONFIG}"]
        healthcheck: # https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck 
            test: ["CMD-SHELL", "[ $$(psql -Aqt -c 'SELECT 1')1 == 11 ] && exit 0 || exit 1"]
            #test: ["NONE"] 
            interval: 5s
            timeout: 2s
            retries: 3
            start_period: 10s
        logging: *default-logopts

services:

    pg1: 
        <<: *default-svc
        hostname: "${PGHA_HOST1}" # valid RFC 1123 https://docs.docker.com/compose/compose-file/#hostname
        volumes: # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
            #- dbp1_data:${PATH_ABS_CTNR_PGDATA}
            - pg1_data:${PATH_ABS_CTNR_PGDATA}
            - pg1_arch:${PATH_ABS_CTNR_PGARCHIVE}
            - pgha_etc:${PATH_ABS_CTNR_PG_ETC}
            #- ${PATH_ABS_VM_ASSETS}/sql:${PATH_ABS_CTNR_PGHOME}/sql

            - type: bind
              source: ${PATH_ABS_VM_ASSETS}/sql
              target: ${PATH_ABS_CTNR_PGHOME}/sql

              # @ Host VM
              # sudo find /mnt/assets -exec sudo chown 70:70 {} \+

            # - ${PATH_CONFIG}:${PG_CONFIG}
        deploy: # https://docs.docker.com/compose/compose-file/compose-file-v3/#deploy 
            replicas: 1
            placement:
                constraints: 
                    - node.labels.pg1 == true

    pg2: 
        <<: *default-svc
        hostname: "${PGHA_HOST2}"
        volumes:
            - pg2_data:${PATH_ABS_CTNR_PGDATA}
            - pg2_arch:${PATH_ABS_CTNR_PGARCHIVE}
            - pgha_etc:${PATH_ABS_CTNR_PG_ETC}
            # - ${PATH_CONFIG}:${PG_CONFIG}
        deploy: # https://docs.docker.com/compose/compose-file/compose-file-v3/#deploy 
            replicas: 1
            placement:
                constraints: 
                    - node.labels.pg2 == true