#!/bin/bash
# -----------------------------------------------------------------------
# Archstore [STORAGE/STORE] library by f06yBEAST 2015
# Two data-centric modes for securely archiving files without passwords. 
# - Process set [source-list] or one file/folder [single-source]
# - Auto encrypt/decrypt per filetype & namespace 
# - Requires [private] keyfiles, and other f06yBEAST library scripts.
# 
# MODEs:   storage/store
# METHODs: 'CREATE'|'EXTRACT'|'PRINT'|'TEST'
# PARAMs: 
#  $1 = {file}|{folder}|{NAME}|basename(.arch)|path(.arch)
#  $2 = ['X'|{extract@folder}|'PRINT'|'TEST']
#  $3 = [{target-archname(@'PRINT'|'TEST')}]
# 
# USAGE: storage|store {PARAMs}
# 
#  {NAME}                  - create  all in *.arch per config
#  {path(.arch)}           - create  all in *.arch per config
#  {file-or-folder}        - create  1 at parent
# 
#  {NAME}        X|{xdir}  - extract all in *.arch per config|{xdir}
#  {path(.arch)} X|{xdir}  - extract all in *.arch per config|{xdir}
#  {NAMEfolder}  X|{xdir}  - extract all in *.arch per config|{xdir}
#  {arch-path}   [{xdir}]  - extract 1 at parent|config|{xdir} **
#  
#     ** With or w/out any {source-list}.arch; 
#         allows for storage create/extract of
#         single-source per foldername, and
#         extract per extracted {source-list}.arch
# 
#  {same-as-create} 'PRINT'|'TEST' [target-archname]  - print|test 
#
#  . {storage|store} 'PRINTPASS'  - toggle print-pass [global]
# -----------------------------------------------------------------------
report() 
{   # report on success/fail
	declare _err=0
	[[ (( $_count_process == 0 )) && ! "$@" ]] && { errMSG "NOTHING processed #[${_count_fail}/${_count_process}]" ; return "$?" ; }
	if [[ "$@" ]] # on fail or globals mode, ...
	then  # show all err flags and open log, if NOT globals mode
		[[ "$_MODE" == 'GLOBALs' ]] || errMSG "$@ #[${_count_fail}/${_count_process}]" ; _err="$?" ; 
		# [[ -r "$_7zLOG" ]] && openedit "$_7zLOG" 
	else  # else inform and delete log
		printf "\n %s\n" "$green SUCCESS $normal #[${_count_success}/${_count_process}]"
		[[ -f "$_7zLOG" ]] && rm "$_7zLOG"
	fi
	return "$_err"
}

process_list()
{
	while IFS='' read -r path || [[ -n "$path" ]]
	do 
		[[ "${path:0:1}" != ';' && -n "$path" ]] && {

			map "$path" ; unset _err ;
						
			# if path is temp/created {source-list}, then delete it and return
			[[ "$_FLAG_TEMP_SOURCE" && "$_basename" == "${_SOURCE##*/}" ]] && { rm "$_SOURCE" ; _err="$_err_persist" ; return 0 ; }
			
			# print_map() or process_path()
			[[ "$_METHOD" == 'PRINT' ]] && {
				
				print_map # out-of-band due to print format

			} || {
			
				printf "  %-25.25s @ %-40.40s" "'${_basename}' $_elips" "${_parent#/cygdrive} $_elips"

				if [[ -e "$_path" ]]
				then 
					process_path "$_path"
				else 
					_err="NOT-EXIST['${_basename}'] "
				fi
				# append [color-block] to above print-line per status [updated/new/no-change/err]
				[[ "$_err" ]] && color=red || color=green         # fail|success
				[[ "$_status" -eq 0 && ! "$_err" ]] && color=gray # no-change 
				[[ "$_status" -eq 2 && ! "$_err" ]] && color=blue # new [target did not exist]
				printf " ${!color}%s${normal}\n" "  " # append color-block & newline
				_err_persist="$_err$_err_persist"     # save/accum err message[s]
				
				# increment count[s] 
				[[ "$_err" ]] && (( _count_fail += 1 )) || { [[ ( "$color" != 'gray' ) || ( "$_METHOD" == 'EXTRACT' ) ]] && (( _count_success += 1 )) ; }
				(( _count_process += 1 ))		
		}	}
	done <<< "$@" # 1 path per line ['Here String']

	# flag cases where nothing in source-list was processed, empty source-list, etc
	[[ "$_ARCHSTORE" && ( $_count_process -eq 0 ) ]] && _err_persist="NOTHING-@-source-list $_err_persist"
	
	_err="$_err_persist"
}

	process_path()
	{
		[[ "$_METHOD" == 'FIND' ]] && { 
			_target="$@"
			[[ "$_target_hex" == "$_archname" ]] && {
			true # TODO ; extract per user-entry of STORAGE source name
			     # I.e., storage 'this storage-archived folder or file name'
				 # (an in-band version of PRINT method str-filter)
			}
		}
		
		[[ "$_METHOD" == 'TEST' ]] && { 
			_status=0
			[[ "$_target_search" ]] && {
				[[ "$( echo "$_path" | grep -i "$_target_search" )" ]] || return 0
			}
			_status=1
			# test archive integrity
			test7z ; return $? 
		}
		
		[[ "$_METHOD" == 'CREATE' ]] && { 
			# flag if its archive is not up-to-date
			flagupdate "$_path" "$_archive_path"
			_status=$? # color per status
			(( $_status )) && { # if flagged for update ...
			
				# del all 'Thumbs.db' in and under path			
				find "$_path" -name 'Thumbs.db' -type f -delete
				
				# create archive ; end on fail
				s7z ; (( $? )) && return $? # err-msg set @ s7z

				# set archname + suffix per mode
				mv "${_path} [s].7z" "${_parent}/${_archname}${_mode_suffix}" > /dev/null 2>&1
				[[ -e "${_parent}/${_archname}${_mode_suffix}" ]] || { _err="NO-ARCHIVE@'${_basename}' " ; return 86 ; }

				#if archive created, move to ARCHSTORE ; flag on move fail 
				[[ "$_ARCHSTORE" ]] && {
					mv "${_parent}/${_archname}${_mode_suffix}" "$_archive_path" > /dev/null 2>&1
					(( $? )) && { _err="mv@'${_basename}' " ; return 86 ; }
				}
		}	}

		[[ "$_METHOD" == 'EXTRACT' ]] && { 
			# get mod-time if extract pre-existing
			# [basename may extract to a nested folder if full-paths option @ 7z-create]
			_extracted="$( findfile "${_EXTRACT_ROOT}/${_basename}" )" # full-depth search
			[[ "$_extracted" ]] && {
				_extracted="$( newest "$_extracted" )"
				declare _mtime1="$( stat -c %Y "$_extracted" 2> /dev/null )"
			}
			
			# extract archive; end on fail
			_PWD="$PWD" # remember [dir change on some fail modes]
			u7z ; _e=$?
			[[ "$_PWD" == "$PWD" ]] || pushd "$_PWD" > /dev/null 2>&1 # ensure dir unchanged
			(( $_e )) && return $_e # err-msg set @ u7z

			# validate extract; flag & end on fail
			_extracted="$( findfile "${_EXTRACT_ROOT}/${_basename}" )" # full-depth search
			[[ "$_extracted" ]] && {
				_extracted="$( newest "$_extracted" )"
				declare _mtime2="$( stat -c %Y "$_extracted" 2> /dev/null )"
			}

			[[ "$_mtime2" ]] || { _err="NO-EXTRACT@'${_basename}' " ; return 86 ; }
			# set status on success @ new->[2] newer->[1] no-change->[0]
			[[ "$_mtime1" ]] && { (( "$_mtime2" > "$_mtime1" )) && _status=1 || _status=0 ; } || _status=2 
	}	}

input_handler() # handle {source-list} or {single-source} input [path]
{
	[[ "$_ARCHSTORE" ]] && {            # if input is source-list, then ...
		process_list "$( <"$_SOURCE" )" # process all sources in source-list file, per path, 
		process_list "$_SOURCE"         # then process source-list file,
	} || process_list "$_SOURCE"        # else process single-source file.
}

# -- RUN --

# config 
clear ; echo
REQUIREs _config_archstore ; source "$_SCRIPTS_FOLDER/_config_archstore"
_config_archstore "$@" ; _e=$? ; [[ "$_err" ]] && _err="${_err} [${_e}]"

# header [inform]
printf " %s\n\n" "${_MODE^^} @ '${_NAME}' [${_METHOD}]" 

[[ "$_err" ]] || input_handler "$@"

# footer [inform]
report "$_err"
