#!/bin/bash
# ---------------------------------------------------------------------
#  [Un]Compress input file|folder|all-subfolder[s] | PIPEd source[s]
# 
#   - call script from library-in-path script having fname=<ext>
#   - archive method hinting per fname of calling script, <ext>
#   - [un]compress per source-file-extension hinting; '*.<ext>'
#   - creates/extracts at/to parent of source-path
#   - accepts piped source-path[s], if no flag [$2] (see 'PARAMs')
# 
#  PARAMs: <source-path> [-1{flag(process-all-subdirs)}]
#   or 
#  PIPEd: 'find ... -print | <ext>'  (expects newline delimiter)
# 
#  [ Calling scripts should bypass to resp. native where apropos. ]
# ---------------------------------------------------------------------
process() 
{  
	REQUIREs flagupdate colors ; colors ; declare _source _target _ext
	# set/validate <ext> per var '_ARCHIVE_HANDLER_TYPE', exported @ calling script 
	for ext in tar tgz txz zip 7z gz; do [[ "$ext" == "${_ARCHIVE_HANDLER_TYPE,,}" ]] && _ext="$ext" ; done
	[[ ! "$_ext" ]] && return 99

	_process_one() {
		_source="${1##*/}" # basename
		pushd "${1%/*}" > /dev/null 2>&1 # pwd => source-parent dir
		if [[ "${1##*.}" != "$_ext" ]] # compress|extract PER EXTENSION
		then # <ext> :: CREATE/UPDATE ARCHIVE
			[[ $( islink $1 ) ]] && return # do not archive symlink folders
			_target="${_source}.$_ext" # target archive path
			# DO NOTHING IF target [archive] exist and up-to-date
			flagupdate "$1" "$_target"
			if [[ "$?" != '0' || ! -e "$_target" ]]
			then # create|update [if target archive not exist or obsolete]
				/bin/tar -caf "$_target" -C "${PWD}" "${_source}" #> /dev/null 2>&1 
				# set target mtime per source
				[[ -f "$_target" ]] && touch -r "$1" "$_target"
				# show status @ created|updated
				[[ -f "$_target" ]] && _status="$green \053 $normal" || _status="$red \041 $normal"
				printf '\n %b\t%s\n' "$_status" "'${_target##*/}'"
			else # show status @ unchanged|up-to-date
				_status="$gray 0 $normal"
				printf '\n %b\t%s\n' "$_status" "'${_target##*/}'" 
			fi
		else # <ext> :: EXTRACT ARCHIVE
			if [[ "$_ext" == '7z' ]]
			then # use 7z; tar FAILed SILENTLY on '.7z', sometimes
				/bin/7z x "$1" -o"${1%/*}"  > /dev/null 2>&1 
			else 
				/bin/tar -xaf "$1" -C "${1%/*}" > /dev/null 2>&1 
			fi 
			# show status @ extracted 
			[[ "$?" == '0' ]] && _status="$green \053 $normal" || _status="$red \041 $normal"
			_fname="${_source}" ; _fname="${_fname/.$_ext/}"
			printf '\n %b\t%s\n' "$_status" "'$_fname'"
		fi
		popd > /dev/null 2>&1 # undo pushd [above]; restore prior pwd
	}

	if [[ -e "$1" ]] 
	# --------------------------------------------------------------------------
	#  if by PARAMs [$@] :: create, update [if newer], or extract, archive[s]
	# --------------------------------------------------------------------------
	then 
		if [[ "$2" == '-1' ]] # 1st-child flag
		then # PROCESS ALL 1st-child [ARCHIVES|FOLDERS
			_source=$( find "$1" -mindepth 1 -maxdepth 1 -type d -print )
			if [[ "$_source" ]] # all 1st-child FOLDERS
			then # if folder[s] exist, then ARCHIVE ALL [folders only]
				printf '\n %s\n' "ARCHIVE all FOLDERS @ '$1/*'"
				echo "$_source" | "$0" # RECURSive script call
			else # if folder[s] NOT exist, then look for "*.<ext>" archives
				_source=$( find "$1" -mindepth 1 -maxdepth 1 -type f -name "*.$_ext" -print )
				if [[ "$_source" ]] # all 1st-child "*.<ext>" ARCHIVES
				then # if archive[s] exist, then EXTRACT ALL
					printf '\n %s\n' "EXTRACT all '*.$_ext' @ '$1'"
					echo "$_source" | "$0" # RECURSive script call
				fi
			fi
		else # PROCESS this source [ARCHIVE|FOLDER|FILE]
			_process_one "$1" 
		fi
	elif [[ ! -t 0 ]]
	# --------------------------------------------------------------------------
	# if by PIPEd :: RECURSive script call @ each path [newline delimited]
	# --------------------------------------------------------------------------
	then
		xargs -I {} "$0" "{}" 
	else 
	# if bad path, show status & report err
		_status="$red \077 $normal"
		printf '\n %b\t%s\n' "$_status" "BOGUS path @ '$1'"
	fi
}

# show script info and end if no args and NOT in pipeline
[[ ! "$1" && -t 0 ]] && { script_info "$0" ; exit 99; } 

process "$@"
