#!/bin/bash
# _config_archstore 
# ------------------------------------
unset _err ; unset _NAME ; unset _EXTRACT_ROOT
shopt -s nocasematch  # ignore case of "$@" string
# ------------------------------------
# LIBRARY OPTIONS [set to enable]
# ------------------------------------
# override default archstore [root-path]
_ARCHSTORE_ROOT=
# override default source-list root [folder-path]
_SOURCES_FOLDER=
# set flag to tarball source before/after 7z create/extract; source <=> .tar <=> .t7z
_POSIX_FLAG=
[[ "$_POSIX_FLAG" ]] && _mode_suffix=' [s].t7z' || _mode_suffix=' [s].7z'
# ------------------------------------
# end LIBRARY OPTIONS
# ------------------------------------

match_archname_to_source() # single-source [archive] @ STORAGE/EXTRACT [mode/method]
{ 	
	declare _target_hex="${1##*/}" # this archive basename [hex32]
	declare color=red
	
	match() # set map() params on match
	{   # read/map/inform @ path[s] until match/key found
		while IFS='' read -r path || [[ -n "$path" ]]
		do 
			[[ ( "${path:0:1}" != ';' ) && ( -n "$path" ) ]] && {
				map "$path"
				clear ; printf "\n %s" "SEARCH for MATCH @ '${_NAME}' :: '${_basename}'"
				[[ "$_target_hex" == "$_archname" ]] && {
					_xMATCHED_BASENAME="$_basename"
					_xMATCHED_KEYPATH="$_keypath"
					_xMATCHED_ARCHNAME="$_archname"
					_NAME="${_archname:0:10}..."
					color=green
					
					return 0 # match found
			}	}
		done <<< "$@" # Here String ; one path per line
		return 99 # no match found
	}
	# case :: per foldername reference only [NO {source-list}.arch was ever created]
	# [allows storage/retrieval indep of any {source-list}.arch]
	_SOURCE="${1%/*}" # set SOURCE [required by map()] to target's folder [path]
	match "$_SOURCE"  # try match of target-hex to map of folder-name
	(( $? )) && {     # if not, then extract/search [for/in] its [expected] source-list ...
	
	# case :: per source-list [extract it per folder-name ref]
		# get/set {NAME} per parent [folder-name]
		_NAME="${1%/*}" ; _NAME="${_NAME##*/}"
		[[ "${_NAME^^}" == "$_MODE" ]] && _NAME='dropbox' # reset if {NAME} = {MODE}
		# get/set SOURCE :: extract source-list per {NAME} [& set method to 'EXTRACT']
		# [upon return, config-archstore resumes per single-source / extract]
		_config_archstore "$_NAME" 'X' ; unset _ARCHSTORE ; unset _xMATCHED_BASENAME	
		[[ -f "$_SOURCE" ]] || return 99 # proceed only if source-list found
		
		# first try matching target-hex to source-list file itself; 
		match "$_SOURCE"                     
		# if no match, then try all sources listed therein ...
		(( $? )) && match "$( <"$_SOURCE" )"
	}
	printf "  %s\n\n" "${!color}  $normal" # append status color-block [found or not]
	
	[[ "$_xMATCHED_BASENAME" ]] && return 0 || return 99
}

_config_archstore()
{   # PARAMs: $1 = {file} | {folder} | {NAME} | basename({MODE}.{NAME}.arch) | path({MODE}.{NAME}.arch) 
    #         $2 = [ 'X'| {path(extract@folder)} | 'PRINT' | 'TEST' ]
	#         $3 = [ {search-string-ONLY-@-PRINT|TEST} ]
	REQUIREs 7z colors cygpath errMSG is_hex32
	# if no param, or mode unset, print script info & exit
	[[ "$_MODE" && "$1" ]] || { script_info "$_SCRIPTS_FOLDER/_archstore" ; exit 99 ; }	
	# init
	_7zLOG="${TMPDIR}/${0##*/}.$$.$( date +%F_[%H.%M.%S] ).7z.log"
	(( _count_process = 0 )) ; (( _count_success = 0 )) ; (( _count_fail = 0 ))
	_mode_suffix_length=${#_mode_suffix}
	_elips="$( printf '.%.0s' {1..77} )"
	# validate keymaker per mode ; persistent config [once per script] ...
	[[ -r "$_MUCK_REF_FOLDER" ]] || { _err='_MUCK_REF_FOLDER' ; return 86 ; }
	[[ "$_MODE" == 'STORAGE' ]] && {
		REQUIREs _config_hmuck ; source "$_SCRIPTS_FOLDER/_config_hmuck"
		hmuck32 -q > /dev/null 
		(( $? )) && { errMSG "hmuck" ; return 86 ; }
	}
	[[ "$_MODE" == 'STORE' ]] && {
		REQUIREs _config_cmuck ; source "$_SCRIPTS_FOLDER/_config_cmuck"
		muck1 -q > /dev/null 
		(( $? )) && { errMSG "cmuck" ; return 86 ; }
	}
	# config GLOBALs :: toggle PRINTPASS & end on 'printpass' @ $1 [run in current shell]
	[[ "${1^^}" == 'PRINTPASS' ]] && { 
		[[ ! "$_PRINTPASS" ]] && { _PRINTPASS=1 ; _err='ENABLED' ; } || { unset _PRINTPASS ; _err='DISABLED' ; } 
		_err="$_err @ ${SHLVL}x bash"
		_MODE='GLOBALs' ; _NAME='PRINTPASS' ; _METHOD="$_err"
		_err="PRINTPASS $_err"
		
		export _PRINTPASS ; return 0 
	}	
	colors # don't invoke before sourced-run [@ GLOBALs], else subsequent set commands are rainbows

	# config per input [$@]; normal [sub-shell] run ...

	per_source_list() 
	{   # set ARCHSTORE & SOURCE per source-list $1, MODE, and METHOD
	    # PARAMs: $1 = {NAME}|{MODE}.{NAME}.arch|path(folder({NAME}))|path(.arch)
		
		# set if not already Env. Var. ...
		#[[ "$_ARCHSTORE_ROOT" ]] || _ARCHSTORE_ROOT="$( cygpath -au "${USERPROFILE}" )/Dropbox"
		[[ "$_ARCHSTORE_ROOT" ]] || _ARCHSTORE_ROOT="$(tr -dc '[[:print:]]' <<< "$( cygpath -au "${USERPROFILE}")")/Dropbox"
		[[ "$_SOURCES_FOLDER" ]] || _SOURCES_FOLDER="${_UNREG_FOLDER}/_archive/_archstore"
		# validate ...
		[[ -d "$_ARCHSTORE_ROOT" ]] || { _err='_ARCHSTORE_ROOT' ; return 86 ; }
		[[ -r "$_UNREG_FOLDER"   ]] || { _err='_UNREG_FOLDER'   ; return 86 ; }
		[[ -d "$_SOURCES_FOLDER" ]] || { _err='_SOURCES_FOLDER' ; return 86 ; }
		
		# set default NAME, ARCHSTORE, SOURCE ...
		
		# set NAME per source-list [$1] ~ [{folder-path}/][{MODE}.]{NAME}[.arch]
		#_NAME="${1:-TEST}"
		_NAME="$1" ; _NAME="${_NAME##*/}" ; _NAME="${_NAME#${_MODE,,}.}" ; _NAME="${_NAME#${_MODE^^}.}"; _NAME="${_NAME%.arch}"
		[[ "${_NAME^^}" == "$_MODE" ]] && _NAME='dropbox' # reset if {NAME} = {MODE}

		_ARCHSTORE="${_ARCHSTORE_ROOT}/${_NAME}"

		# set SOURCE to source-list [.arch] path [default to expected @ sources-folder]
		_SOURCE="${_SOURCES_FOLDER}/${_MODE,,}.${_NAME,,}.arch"
		
		# conditionally reset ARCHSTORE and/or SOURCE per NAME/MODE/METHOD/$1
		case "${_NAME,,}" in
			'work')
				#_ARCHSTORE="$(cygpath -au 'S:\SCRATCH\[WORK]\[store]' )"
				_err=TODO[versioning-sans-encrypt] 
				;;
			'cmdlib')
				_ARCHSTORE="${_ARCHSTORE_ROOT}/${_MODE}"
				;;
			'dropbox') # reset per MODE
				_ARCHSTORE="${_ARCHSTORE_ROOT}/${_MODE}"
				;;
			*)  # reset SOURCE [source-list] to $1 if default not exist ...
				[[ -e "$_SOURCE" ]] || _SOURCE="$1" # may not exist [yet] either
				;;
		esac
		
		# @ CREATE :: make new ARCHSTORE [dir] if not exist but SOURCE exist
		[[ "$_METHOD" == 'CREATE' ]] && {
			[[ -d "$_ARCHSTORE" ]] || { 
				[[ -e "$_SOURCE" ]] && mkdir "$_ARCHSTORE"
		}	}
		
		# @ EXTRACT|TEST :: get/set {source-list} of all archives @ $1 [path or archstore-reference]
		[[ ( "$_METHOD" == 'EXTRACT' || "$_METHOD" == 'TEST' ) && ( -d "${1}" || -d "$_ARCHSTORE" ) ]] && { 
			
			# if $1 is folder [of archives], then reset archstore to it
			[[ -d "${1}" ]] && _ARCHSTORE="${1}"
			
			# @ STORAGE, find/get/set SOURCE [source-list] for archives in NAME folder
			[[ "$_MODE" == 'STORAGE' ]] && {
				# if source-list not exist @ sources-folder, then try find/extract it @ ARCHSTORE
				[[ -e "$_SOURCE" && ! -d "$_SOURCE" ]] || _SOURCE="${_ARCHSTORE}/${_MODE,,}.${_NAME,,}.arch"
				# if source-list not [yet] exist, then try extracting it from its [expected] archive @ ARCHSTORE
				[[ -e "$_SOURCE" && ! -d "$_SOURCE" ]] || {
					# set map params for the expected archive of source-list 
					map "${_ARCHSTORE}/${_MODE,,}.${_NAME,,}.arch"
					[[ -e "${_ARCHSTORE}/$_archname" ]] && {
						# inform user of source-list archive extraction
						printf "\n %s\n\n" "EXTRACTING '${_archname:0:10}...' [${_basename}]" 
						_EXTRACT_ROOT="$_ARCHSTORE"	
						u7z # extract {source-list}.arch
					} || { _err="source-list-NOT-EXIST@'${_NAME}'" ; }
					# validate source-list ; flag on fail
					[[ -e "$_SOURCE" ]] || _err='NO-source-list'
				}
			}
			# @ STORE, set SOURCE to {archive-list} file containing all arch-paths @ ARCHSTORE
			[[ "$_MODE" == 'STORE' ]] && {
				_SOURCE="${TEMP}/${0##*/}.SOURCE.${_NAME}.$( date +%F_[%H.%M.%S] )"
				(> "$_SOURCE" ) # create empty file
				while IFS='' read -r 
				do
					# print to SOURCE file all paths in ARCHSTORE having namespace per store mode
					[[ "${REPLY:(-$_mode_suffix_length)}" == "$_mode_suffix" ]] && printf "%s\n" "$REPLY" >> "$_SOURCE" 
				# '<<<' is Here-string syntax ; "$(...)" is string containing all paths [1 per line]
				done <<< "$( ls -d "${_ARCHSTORE}/"* 2> /dev/null )" 
				_FLAG_TEMP_SOURCE=1 # flag this temp SOURCE creation [ugly hack for process_list()]
			}
		}

		# (re)set err on fail of SOURCE or ARCHSTORE
		[[ "$_err" ]] && return 99
		[[ -e "$_SOURCE"    ]] || { _err="SOURCE-per-source-list-@-'${_SOURCE##*/}'" ; return 99 ; }
		[[ -d "$_ARCHSTORE" ]] || { _err="ARCHSTORE@'$_ARCHSTORE'"  ; return 99 ; }

		return 0
	} 
	
	is_arch() 
	{   # prints '1' if $1 is archive per storage|store mode namespace, else silent
		declare _basename="${1##*/}"
		is_hex32 "${_basename}" ; _hex32=$?
		[[ "$_MODE" == 'STORAGE' ]] && { [[ $_hex32 -ne 0 ]] && echo '1' ; }
		[[ "$_MODE" == 'STORE'   ]] && { [[ "${_basename:(-$_mode_suffix_length)}" == "$_mode_suffix" ]] && echo '1' ; }
	}
	
	# set METHOD to 'CREATE'|'EXTRACT'|'PRINT' per input [$@]
	_METHOD='CREATE'
	# reset if $2 exists or is 'X'
	[[ -e "$2" || "${2^}" == 'X' ]] && _METHOD='EXTRACT'
	# reset if $1 is archive file in namespace per mode
	[[ "$( is_arch "$1" )" ]] && {
		_METHOD='EXTRACT'
		# if STORAGE mode, then match archname to its source per {NAME} @ parent foldername 
		[[ "$_MODE" == 'STORAGE' ]] && {
			match_archname_to_source "$1"
			[[ "$_xMATCHED_BASENAME" ]] || _err="NO MATCH FOUND @ '$_NAME'"
	}	}
	# reset to print-only method if 'PRINT' @ $2  ; filter per target-search string @ $3
	[[ "${2^^}" == 'PRINT' ]] && { _METHOD='PRINT' ; _target_search="$3" ; }
	[[ "${2^^}" == 'TEST'  ]] && { _METHOD='TEST'  ; _target_search="$3" ; }
	
	# catch bad extract path input [$2]
	[[ "$_METHOD" == 'CREATE' && "$2" ]] && { _err='BAD-extract-PATH' ; _METHOD='EXTRACT' ; }
	
	# set SOURCE [path] per {source-list} or {single-source} input [$1]
	_SOURCE="$1"
	[[ "${1##*.}" == 'arch' || ! -e "$1" ]]  && per_source_list "$@" 
	[[ -d "$1" && ( "$_METHOD" == 'EXTRACT' || "$_METHOD" == 'TEST' ) ]] && per_source_list "$@" 
	[[ "$_NAME" ]] || _NAME="${_SOURCE##*/}" # if NAME not set, then set to source basename
	
	[[ "$_err" ]] && return 99

	# set EXTRACT-ROOT per $2 [ 'X' or {folder} ]
	[[ "$_METHOD" == 'EXTRACT' ]] && {
		if [[ -d "$2" ]]
		then # if $2 is a folder, extract to it [override default] [all cases]
			_EXTRACT_ROOT="$2"
		else # if $2 is 'X' ...
			if [[ "$_ARCHSTORE" ]] 
			then # if per source-list, extract to its archstore
				_EXTRACT_ROOT="${_ARCHSTORE}"
			else # if per single-source, extract to its parent
				_EXTRACT_ROOT="${_SOURCE%/*}"
			fi
		fi
		# validate extract-root
		[[ -d "$_EXTRACT_ROOT" ]] || _err="xfolder '$_EXTRACT_ROOT'"
	}
	
	[[ "$_err" ]] && return 99 || return 0
}

map()  # PARAMs: {path; POSIX or Windows syntax}
{      # maps this path, $@, to archstore params 
	
	[[ "$@" ]] || return 99
	#[[ "$_target_search" && "$_print_this" ]] && return 0 # end @ first found
	
	_path="$( cygpath -au "$@" )" # Windows => POSIX syntax
	_parent="${_path%/*}"         # parent folder in POSIX syntax
	_basename="${_path##*/}"      # {file-or-folder-name.ext}
			
	[[ "$_MODE" == 'STORE' ]] && {
		_basename=${_basename%"$_mode_suffix"} # any mode
		_keypath="$_basename"
		_archname="$_basename"
	}
	
	[[ "$_MODE" == 'STORAGE' ]] && { 
		unset _mode_suffix
		# if SOURCE or .arch, then set key per basename, else per absolute path [Windows syntax]
		[[ "$_path" == "$_SOURCE" || "$_basename" == "${_MODE,,}.${_NAME,,}.arch" ]] && _keypath="$_basename" || _keypath="$( cygpath -aw "$@" )"
		_archname="$( hmuck32 -q "$_keypath" )"
		
		[[ "$_xMATCHED_BASENAME" ]] && { 
			# reset on matched @ config EXTRACT of {single-source} [hex32] input
			_basename="$_xMATCHED_BASENAME"
			_keypath="$_xMATCHED_KEYPATH"
			_archname="$_xMATCHED_ARCHNAME"
		}
	}

	# set archive-path ; root per source-list or single-source
	[[ "$_ARCHSTORE" ]] && _archive_path="${_ARCHSTORE}" || _archive_path="${_parent}"
	_archive_path="${_archive_path}/${_archname}${_mode_suffix}"

	# if EXTRACT method, reset path to archive-path 
	[[ "$_METHOD" == 'EXTRACT' ]] && _path="$_archive_path"	
	[[ "$_METHOD" == 'TEST'    ]] && _path="$_archive_path"	

	#[[ "$_METHOD" == 'PRINT' ]] && print_map 
	
	[[ "$_archname" ]] || return 86 # 86 should never happen	
}

print_map() # print map of this path [$@] ; filter if target-search set
{ 
	print1()
	{
		printf "\n %s\t%s\n" "id" "'$_basename'"
		printf " %s\t%s\n" "path" "'$( cygpath -aw "$_path" )'"
		printf " %s\t%s\n" "arch" "$_archname"
		if [[ "$_PRINTPASS" ]]
		then
			[[ "$_MODE" == 'STORE'   ]] && _key="$( muck5 -q "$_keypath" )"
			[[ "$_MODE" == 'STORAGE' ]] && _key="$( hmuck -q "$_keypath" )"
			printf " %s\t%s\n" "pass" "$_key" ; _key=$?
		fi
		printf " %s" ; printf  "%.1s" '-'{1..40} ; echo ; 
	}	
	if [[ "$_target_search" ]]
	then # print new header and all target match[es] found so far
		clear ; printf "\n %s\n" "${_MODE^^} @ '${_NAME}' [${_METHOD}] :: '$_target_search' in PATH @ '$_basename'"
		if [[ "$( echo "$_path" | grep -i "$_target_search" )" ]]
		then # if match, append to print-str, count+, and send arch-path to clipboard
			_print_all="${_print_all}$( print1 )" 
			putclip "'$_archive_path'"
			[[ "$_archname" ]] && (( _count_success += 1 ))
		else 
			(( _count_fail += 1 )) # count+ unmatched
		fi
		echo "$_print_all" # print map[s] of target-search match[es]
	else # unfiltered print [all maps / all in source-list]
		print1 # print this map ; count+ success|fail
		[[ "$_archname" ]] && (( _count_success += 1 )) || (( _count_fail += 1 ))
	fi
	(( _count_process += 1 ))
	
	return 0
}
	
key()
{
	unset _key
	[[ "$_MODE" == 'STORE'   ]] && { _key="$( muck5 -q "$_keypath" )" ; return 0 ; }
	[[ "$_MODE" == 'STORAGE' ]] && { _key="$( hmuck -q "$_keypath" )" ; return 0 ; }
	
	return 86
}

s7z() # create archive
{  
	declare _7z_source
	
	# tar :: create
	[[ "$_POSIX_FLAG" ]] && {
		7z a "${_path}.tar" "$_path" >> "$_7zLOG" 2>&1
		(( $? )) && { _err="s7z-tar[$?]@'${_basename}' " ; return 99 ; }
		_7z_source="${_path}.tar"
	} || { _7z_source="$_path" ; }
	
	# 7z :: create/overwrite [auto-encrypt] [set arch mtime to that of newest therein]
	key ; [[ "$_key" ]] || { _err="s7z-key@'${_basename}' " ; return 87 ; }
	7z a -stl -mhe=on -p"${_key}" "${_path} [s].7z" "$_7z_source" >> "$_7zLOG" 2>&1

	# delete tar if exist
	_key="$?" ; [[ "$_7z_source" != "$_path" ]] && rm "$_7z_source"
	(( $_key )) && { _err="s7z[$_key]@'${_basename}' " ; return 99 ; }
	
	return 0 # on success
}

# 7z Exit Codes ...
#  0 - Normal [no errors/warnings]
#  1 - Warning [Non-fatal error(s)], e.g., some files not accessible
#  2 - Fatal error
#  7 - Bad parameters
#  8 - Not enough memory

u7z() # extract archive [on fail, may return in different dir]
{
	pushd "$_EXTRACT_ROOT" > /dev/null 2>&1 # cuz 7z...-o{xfolder} fails some cases
	[[ "$_EXTRACT_ROOT" == "$PWD" ]] || { _err="u7z[pushd@'$_EXTRACT_ROOT'] " ; return 87 ; }
	
	# 7z :: extract/overwrite [auto-decrypt]
	key ; [[ "$_key" ]] || { _err="u7z-key@'${_basename}' " ; return 87 ; }
	7z x -p"$_key" -y "${_path}" >> "$_7zLOG" 2>&1 
	
	# tar :: extract if [exist] POSIX_FLAG set ; delete .tar file on success
	_key="$?" ; (( $_key )) && { _err="u7z[$_key]@'${_basename}' " ; } || {
		[[ "$_POSIX_FLAG" ]] && { 
			7z x -y "${_EXTRACT_ROOT}/${_basename}.tar" >> "$_7zLOG" 2>&1 
			_key="$?" ; (( $_key )) || rm "${_EXTRACT_ROOT}/${_basename}.tar"
		} 	
		(( $_key )) && _err="u7z-tar[$_key]@'${_basename}' "
	}
	popd > /dev/null 2>&1
	
	return $_key # 7z exit-code
}

test7z() # test archive integrity
{
	key ; [[ "$_key" ]] || { _err="u7z-key@'${_basename}' " ; return 87 ; }
	
	7z t -p"$_key" -y "${_path}" >> "$_7zLOG" 2>&1 

	_key="$?" ; (( $_key )) && { _err="test7z[$_key]@'${_basename}' " ; return 99 ; }

	return $_key # 7z exit-code
}
