#!/bin/bash
# ----------------------------------------------------
#  arch :: library 'store' || native 'arch', per $@
# ----------------------------------------------------
if [[ "$@" ]] 
then 
	store "$@"
else  
	echo; echo '  ... RUNs store [library script] if arg[s] exist'; echo
	[[ "$( type -t /bin/arch )"      ]] && { /bin/arch ; exit ; }
	[[ "$( type -t /usr/bin/arch  )" ]] && { /usr/bin/arch ; exit ; }
fi

exit
 