#!/usr/bin/env bash
_archive() {( 
    # PARAMs: SOURCE-PATH
    # archive source [$1(default@$_HOME)] on any change, or on "x"
    [[ -d "$_ETC_ARCHIVES_FOLDER" ]] || { errMSG '_ETC_ARCHIVES_FOLDER does NOT EXIST'; exit 86 ; }
    
    REQUIREs tar tgz errMSG colors flagupdate ; colors
    # set source path
    case ${1,,} in  # scripted per-name [$1] sources
         'etc')   _source="$_HOME/etc" ;;
        'home')   _source="$_HOME/etc" ;;
                 *)   _source="$1" ;;
    esac
    # if _source [$1] not exist, then default to HOME/etc
    [[ ! -e "$_source" ]] && _source="$_HOME/etc"
    # set fname-prefix per source; @ HOME, use "HOST.OSTYPE.USER.etc"
    #[[ "$_source" == "$_HOME/etc" ]] && { _name="${HOSTNAME}.${USERNAME// /-}.etc"; } || { _name="$( basename "$_source" )"; } 
    _name="$( basename "$_source" )"  # same HOME archive for all platforms and users
    # make new arch if arch older than source or not exist, or on any arg
    alias ls=ls  # undo any alias
    
    newest_archive="$( ls -tr "${_ETC_ARCHIVES_FOLDER}/${_name}"*.t?z 2> /dev/null | tail -n 1 )"
    timestamp "$_source" 1 > /dev/null  
    flagupdate "$_source" "$newest_archive"
    if [[ $? -gt 0 || "$1" == "x" ]]
    then 
        #history -c; echo > "$_HOME/.bash_history" # clear user history [belt & suspenders]
        funcname=${FUNCNAME^^}
        printf "\n %s\n"  "${gray} ${funcname:-$1} ${normal}"
        
        # Update and store home DOT FILE archives if source is ~/etc
        [[ "$_source" == "$_HOME/etc" && "$_ARCHIVE_DOT_FILES" ]] && { 
            storeroot 
        }
        # ARCHIVE source to archives-folder; method per ext
        # LZMA2 @ tar.xz <=> txz | bzip2 @ tar.gz <=> tgz
        _target=${_ETC_ARCHIVES_FOLDER}/"$_name.$(date +%F_[%H.%M.%S])".tgz
        # txz bug @ linux; archives first/last arch in scripts; '[dev].7z'
        [[ "$_source" ]] && printf "\n  %s\n" "SOURCE:  '${_source##*/}'"
        [[ "$_target" ]] && printf "  %s\n"   "TARGET:  '${_target##*/}'"
        
        tar -caf "${_target}" -C "${_source%/*}" "${_source##*/}" 
        [[ -e "$_target" ]] && touch -r "$_source" "$_target"  
        _arch_at_storage="/d/1 Data/Archive/PRJ/IT/Platform/HOME/$HOSTNAME"
        [[ -d "$_arch_at_storage" ]] && \
        cp "$_target" "$_arch_at_storage/${_target##*/}"

        err=$?
        # rpt on success/fail
        [[ "$err" == '0' ]] && {
            _s="$green SUCCESS $normal"
        } || {
            _s="$red FAIL :: ERR[$err] $normal"
        }
        printf "\n %s\n\n" "$_s"
        exit $err
    fi
)}

_archive "$@"