#!/usr/bin/env bash
# ---------------------------------------------------------------
#  Remove ICON="*" from Firefox-exported "*.html" file,
#  and save to "*-[sans-ICON].html". Source file unchanged.
# 
#  ARGs: FILE  
# ---------------------------------------------------------------
[[ "$1" ]] || { script_info "$0"; exit 99; }

sed -e 's/ICON=".*"//' "$@" > "${@%.*}-[sans-ICON].html"
