#!/bin/bash

dellogs()
{   # PARAMs: {dir-path}
	REQUIREs push pop
	# init :: pushd & validate target dir
	push "$@" ; clear; echo
	[[ "$PWD" == "$@" ]] || { echo "  PARAMs: {dir-path}" ; return 99 ; }
	[[ -e "$@" && ! ( "${1///}" == '' || "${1//.}" == '' ) ]] || { echo "  Path name required" ; return 99 ; }

	for file in *.log
	do # overwrite/rename/del all log files @ current dir
		[[ "$file" == '*.log' ]] && break   # if none
		(( count += 1 ))
		head -c 100K /dev/urandom > "$file" # overwrite
		mv "$file" "$$.$count.LOL"          # rename
		[[ -f "$$.$count.LOL" ]] && rm "$$.$count.LOL" # delete
		printf "[%-4.4d]  '%s'\n" "$count" "$file"     # inform
	done
	pop
}
# -- RUN --

dellogs "$@"
