#!/usr/bin/env bash
# -------------------------------------------------------------
#  cat A B B |sort |uniq -u 
# 
#  Lists the positive residual: (A - B); then does (B - A).
#     
#  ARGs: A B  (file paths)
# -------------------------------------------------------------
[[ "$2" ]] || { script_info "$0"; exit 99; }

clear

echo -n '===  (A - B)  === [ENTER]' 
read p

cat "$1" "$2" "$2" |sort |uniq -u 

echo ''
echo -n '===  (B - A)  === [ENTER]'
read p

cat "$2" "$1" "$1" |sort |uniq -u