#!/bin/bash
clear; echo
# --------------------------------------------------------------------
#  A 'Percent Entropy' Metric :: Compression Ratio ( file.gz / file )
# 
#  PARAM: <file-path> | <str> | <#(1-6)>  { refs, per entRef() }
# 
#  (Worthless for very small files or very short strings)
# --------------------------------------------------------------------
_type='gz'

entFile() { # PARAMs: <file-path>
	7z a "${@##*/}.$_type" "$@" > /dev/null
	# stat -c %s "$TMPDIR/${@##*/}.$_type"
	_c=$( wc -c < "$TMPDIR/${@##*/}.$_type" )
	_u=$( wc -c < "$@" )
	_r=$(( 100 * $_c / $_u ))

	printf "\n %s\t%s\n" "ENTROPY: $_r%	($_c/$_u)" 
}

entString() { # PARAMs: <str> 
	# gzip string input
	_u="$@" ; _u=${#_u}
	_c=$( printf "$@" | gzip -cf ) ; _c=${#_c}
	_r=$(( 100 * $_c / $_u ))	
	printf "\n %s\t%s\n" "ENTROPY: $_r%	($_c/$_u)" 
}

entRef() { # PARAMs: <#(1-6)>

	# -- ref 1 --

	case $1 in
	   "1") # '000...'
			printf "\n %s\n\n" "#$1 '000...' vs. /dev/urandom" 
			for (( i = 0 ; i < 10000; i++ )) ; do printf '0' ; done > 1.log 	   
			;;
	   "2") # hex :: sha256 (0-#)
			printf "\n %s\n\n" "#$1 SHA2(RANDOM % 32000) vs. /dev/urandom  {does NOT improve w/ size}" 
			for (( i = 0 ; i < 80; i++ )) ; do printf "$( sha256 -q $(( RANDOM % 32000 )) )" ; done > 1.log 
			;;
	   "3") # random 0-9
			printf "\n %s\n\n" "#$1 RANDOM(0-9)) vs. /dev/urandom" 
			for (( i = 0 ; i < 100000; i++ )) ; do printf "$(( RANDOM %  10 ))" ; done > 1.log 
			;;
	   "4") # random 0-15
			printf "\n %s\n\n" "#$1 RANDOM(0-15) vs. /dev/urandom" 
			for (( i = 0 ; i < 100000; i++ )) ; do printf "$(( RANDOM %  16 ))" ; done > 1.log 
			;;
	   "5") # random 0-99
			printf "\n %s\n\n" "#$1 RANDOM(0-99) vs. /dev/urandom" 
			for (( i = 0 ; i < 55000; i++ )) ; do printf "$(( RANDOM % 100 ))" ; done > 1.log 
			;;	   
       "6") # ASCII(RANDOM 255) ... just a very, very slow mimic of /dev/urandom
			printf "\n %s\n\n" "#$1 ASCII(RANDOM(0-255)) vs. /dev/urandom" 
			for (( i = 0 ; i < 4096; i++ ))        # Nx
			do 
				_r="$(( RANDOM % 255 ))"            # random 0-255 [decimal]
				_ASCII="$( printf "\\%.3o" "$_r" )" # 3-digit octal equiv [000-377] w/ prepended '\'
				printf "%b" "$_ASCII"               # interpret the code "\ccc"
			done > 1.log
			;;	   
	   *) return 99
			;;
	esac

	# -- ref 2 --
	
	# /dev/urandom
	cat /dev/urandom | head -c $(( 1000000 )) > 2.log

	# 1 vs. 2 
	entFile '1.log'
	entFile '2.log'
}

pushd "$TMPDIR" > /dev/null

[[ ! "$1" ]] && { script_info "$0"; exit ; }         # script info

[[ -f "$1" ]] && { entFile "$@" ; exit ; }           # file

[[ -z "${1//[1-6]}" ]] && { entRef  "$1" ; exit ; }  # ref # 1-5

entString "$@"                                       # string

popd > /dev/null

exit 0
