#!/bin/bash
exif()
{(  # ExifTool wrapper :: handle file or folder; optionally filter
	# PARAMs: [AUDIO|VIDEO] {path(dir|file)}
	PATH="$_UNREG_FOLDER/ExifTool:$PATH" # add ExifTool program-path to PATH 
	REQUIREs exiftool push pop # end if any required don't exist
	
	printExif() # read Exif in $@, and print per filter
	{   # PARAMs: {file-path} 
	    # PRESETs: _filter[@]
	    # REQUIREs push pop 
		# get Exif data [push/pop dir needed here, else 'File not found' @ exiftool on local files]
		[[ -f "$@" ]] && { push "${@%/*}" ; _Exif="$( exiftool "${@##*/}" )" ; pop ; } 	
		# print data per filter
		for (( i = 0 ; i < ${#_filter[@]};  i++ )) ; do echo "$_Exif" | grep "${_filter[$i]}" ; done
	}
	
	# set filter [array]
	_filter=(':') # default @ unfiltered ; print all
	# reset filter on keyword input @ $1 
	[[ -e "$1" ]] || {
		[[ "${1,,}" == 'video' ]] && { _filter=( 'File Name' 'Video' 'Encoding' 'Image' 'Audio' ) ; shift ; }
		[[ "${1,,}" == 'audio' ]] && { _filter=( 'File Name' 'Bitrate' 'Sample Rate' 'Mode' 'Album' 'Artist' 'Band' 'Genre' 'Title' 'Year' ) ; shift ; }
	}
	# process $@ per dir|file
	[[ -e "$@" ]] || return 99
	[[ -f "$@" ]] && printExif "$@"
	[[ -d "$@" ]] && { for f in "$@/"*.* ; do { echo ; printExif "$f" ; } done ; }
)}
# -- RUN --

exif "$@"
