#!/bin/bash
# --------------------------------------------------------------------- 
#  Config FFmpeg @ Cygwin or MINGW
#  - PREPEND path of FFmpeg binaries to $PATH Env.Var.
#  - This script is BYPASSED (and UNNECESSARY) 
#    if FFmpeg installed per Chocolatey or Linux (WSL)
# 
#   >>>  RUN as SOURCE  ::  `. ffmpeg`  <<<
# --------------------------------------------------------------------- 
[[ "$0" != "$BASH_SOURCE" ]] && _isSourced=1  # test/flag :: is run as source

_ffmpeg() {
  # if not run as source, show script info and abort
  [[ ! "$1" ]] && { [[ "$_isSourced" ]] || { script_info "$0"; return; } }
  # set/validate program path
  _ffmpeg_path="$_CYGDRIVE/c/Program Files/FFmpeg/bin"
  [[ -e "$_ffmpeg_path" ]] || {
    _ffmpeg_path="$_CYGDRIVE/c/ProgramData/chocolatey/lib/ffmpeg/tools/ffmpeg/bin"
    [[ -e "$_ffmpeg_path" ]] || { errMSG 'Program path NOT EXIST'; return; }
  }

  # prepend program path to $PATH Env.Var. if not already
  [[ $( printf %s "$PATH" | grep -i 'FFmpeg/bin' ) ]] || {
    PATH="${_ffmpeg_path}:$PATH"
    printf "\n  %s\n" "FFmpeg path PREPENDED to \$PATH" 
  }
}

examples() { # NOT EXECUTED

  # Convert jpg to png file or all @ folder
  [[-f "$@" ]] && ffmpeg.exe -i "$@" "${@%.*}.png" -y -hide_banner  
  [[-d "$@" ]] && find "$@" -type f -iname '*.jpg' -exec "$0" {} \;

  # extract frames from video 
  for i in $(seq -f "%02g" 0 59)  
  do # one frame per minute; 00 - 59 min
    ffmpeg -ss 00:$i:00 -i in.mkv -vframes 1 $i.jpg
  done

  # equivalent, per pipe
  seq -f "%02g" 0 59 | xargs -I {} ffmpeg -ss 00:{}:00 -i in.mkv -vframes 1 {}.jpg

  # -ss/-t [START/DURATION]
  # IN SEEKing; very FAST, but timestamps reset to zero, so `-t`
  ffmpeg -ss 02:14:53 -i IN.mp4 -t 00:36:03 -c copy OUT.mp4  
}

_ffmpeg "$@"