#!/usr/bin/env bash
# ---------------------------------------------------
#  Modify fname(s) of all FILEs @ PWD (no recurse).
# 
#  PARAMs: REMOVE  [REPLACE]
# ---------------------------------------------------
[[ ! "$1" ]] && { script_info "$0"; exit; }
export _rm="$1" 
export _rp="$2" 
find . -maxdepth 1 -name '*'"${_rm}"'*' -execdir /bin/bash -c 'mv "$@" "${@/${_rm}/${_rp}}"' _ {} \;

exit 

# === FOLDERNAMES 

# rm :: test
find . -maxdepth 1 -type d -name '* \[dev\]' -exec /bin/bash -c 'sed "s#\[.*\]##g" <<< "$@"' _ {} \;

find . -type d -iname '*\(\)*' -exec /bin/bash -c 'sed "s#()##g" <<< "$@"' _ {} \;

# rm :: do
find . -maxdepth 1 -type d -name '* \[dev\]' -exec /bin/bash -c 'mv "$@" "$( sed "s#\[.*\]##g" <<< "$@" )"' _ {} \;

find . -type d -name '*\(\)*' -exec /bin/bash -c 'mv "$@" "$( sed "s#()##g" <<< "$@" )"' _ {} \;

# remove trailing space
find . -maxdepth 1 -type d -name '* ' -exec /bin/bash -c 'mv "$@" "${@/ //}"' _ {} \;