#!/bin/bash
# ------------------------------------------------------------- 
#  GitHub :: Wrapper for account-related actions
# 
#   ==========================================================
#   >>>  @ ssh|mode, RUN as SOURCE  ::  `. github {ARGs}`  <<<
#   ===========================================================
# 
#  ARGs: 
#   
#   commitall [(un)quoted-commit-msg]  - add/commit
#   ssh [private-key(default@config)]  - login per ssh key
#   ssh [kill]              - kill all ssh-agent processes
#   mode [ssh|https]       - remote access mode [per repo]
#   config                                          - show
# ------------------------------------------------------------- 
[[ "$0" != "$BASH_SOURCE" ]] && _isSourced=1

_github() {
  REQUIREs git; (( $? )) && return 86; 
  [[ ! "$1" ]] && { [[ "$_isSourced" ]] || { script_info "$0"; return; } }
 
  # @ ssh kill :: all ssh-agent processes
  [[ "$1" == 'ssh' && "$2" == 'kill' ]] && { 
    ps | grep 'ssh-agent' | awk '{print $1;}' | xargs kill 2> /dev/null
  }
  # @ ssh [private-key(else default)]
  # start ssh-agent [bkgnd process]; load private key into it; login
  # ssh-agent handles key-passphrase [if exist] too; regardless, ssh requires
  # UPDATE: No! ssh-agent NOT required if sans key-passphrase;
  #         BUT, need to add public-key [per host] @ ~/.ssh/config
  [[ "$_NOPE_DONT_NEED_THIS_BLOCK" && "$1" == 'ssh' && "$2" != 'kill' ]] && {  
    _isRunning=$( ps | grep 'ssh-agent' )
    [[ "$_isRunning" ]] && { printf "\n  %s\n"  'ssh-agent is RUNNING already'; return 0; }
    REQUIREs ssh-agent; (( $? )) || {
      eval "$(ssh-agent -s)"
      _private_key="$2"
      [[ "$_private_key" ]] || _private_key='github_rsa'
      ssh-add "$HOME/.ssh/$_private_key"
      ssh -T git@github.com # login/connect
    }
  }

  # ssh :: login + set mode
  [[ "$1" == 'ssh' && "$2" != 'kill' ]] && {  
    [[ ! "$_isSourced" ]] && { errMSG 'RUN as SOURCE'; return; }
    printf "\n  %s\n\n" 'SSH login ...'
    [[ $_SSH_GITHUB ]] && { 
      printf "\n  %s\n\n" 'Already connected !'
    } || { 
      # private-key set per arg, else default
      [[ "$2" ]] && ssh-add "$HOME/.ssh/$2"  
      # login/connect, sans pseudo-terminal
      ssh -T git@github.com  
      # set mode to SSH if @  repo, else inform   
      [[ $( find -type d -iname .git ) ]] && {
        printf "\n  %s\n\n" 'set MODE to SSH [per repo!]...'
        $FUNCNAME mode ssh 
        _SSH_GITHUB=1
      } || {
        printf "\n  %s\n\n" 'MUST be @ repo to SET MODE [to SSH]'
      }
    }
  } 

  # @ 'mode [ssh|https]' :: per repo (re)set|show remote access mode
  [[ "$1" == 'mode' ]] && { 
    [[ "$2" &&  ! "$_isSourced" ]] && { errMSG 'RUN as SOURCE'; return; }
    _USERNAME=$( git config --global user.name )
    [[ "$_USERNAME" ]] && {
      # per ssh
      [[ "$2" == 'ssh' ]] && {
        git remote set-url origin git@github.com:${_USERNAME}/${PWD##*/}.git
      }
      # per https
      [[ "$2" == 'https' ]] && {
        git remote set-url origin https://github.com/${_USERNAME}/${PWD##*/}.git
      }
    }
    git remote -v # show current mode
  }

  # @ 'commitall [commit-msg]' :: add all, commit [msg per $2+ else `todaynow`], then push 
  [[ "$1" == 'commitall' ]] && { 
    [[ $2 ]] && { # handle unquoted commit-msg
      shift ; _msg="$@"
    } || { # "YYYY-MM-DD [HH.MM.SS]", if no commit-msg arg
      REQUIREs todaynow; (( $? )) && return 86; 
	    _msg=$( todaynow ); _msg="${_msg/_/ }"
    } 
    git add . ; git commit -m "$_msg" #; git push 
  } 

  # @ 'config' :: show 
  [[ "$1" == 'config' ]] && { 
    git config --list
  }
}

_github "$@"
