#!/bin/bash
# ----------------------------------------------------------------------
#  GnuPG wrapper :: action per param[s]  | Cygwin 2.874 | GnuPG 1.4.20
#                                        | f06yBEAST 2016 
#  PARAMs :: <action> $2 $3 ...      
# 
#    encrypt <file> <recipient>
#    decrypt <file> [<user|keyID>]
#    sign <datafile>
#    detach <datafile>
#    verify <sigfile> [<datafile>]
#    version
#    help [<search>]
#    list [secret] [<keyID>]
#    homedir|dir
#    packets
#    primary [<keyID>] - test keyring for Primary-Secret-Key
#    export [secret|subkeys] - to 'armor' encrypted [*.asc] 
#    gen [batch [test|commit]] - generate new pub/sec pair/keyring
#    arch [<describe>] - zip of * [s].7z encrypted keyring folder
#    edit [<keyID>] - addkey, delkey, fpr, list, toggle, trust, ...
#    fpr [<keyID>] - show Primary (public) key fingerprint; 160-bit
#    revoke - create a revoke-certificate
#    strip [raw] - remove Primary secret key from keyring
#    pipe - pipe passphrase; show global state; GPG_PIPE_PASS {1|0}
# 
#  REQUIREs: push pop todaynow errMSG colors [functions] 
#            and '_agentX' [variable] set if 'GPG_PIPE_PASS' set 
# 
#  GLOBALs:  export GNUPGHOME=/cygdrive/s/test
#            export GPG_KEY=<fingerprint>[!]
#            export GPG_PIPE_PASS=1
#            export _agentX=<agent-script>
#  To MANUALLY pipe passphrase @ command line ... 
#    echo '<passphrase>' | gpg --passphrase-fd 0 <other-gpg-options>
# ----------------------------------------------------------------------

# == FUNCTIONS [gpg.exe actions] ==

encrypt() { 
	_GnuPG --output "${1}.gpg" --recipient "$2" --encrypt "$1"
	_status "${1}.gpg"
}
decrypt() { # decrypts per default key; override @ $2 (user-id|key-id)
	[[ "$2" ]] && _user="--local-user $2" || unset _user
	_GnuPG --output "${1%.gpg}" $_pipe_pass $_user --decrypt "$1"
	_status "${1%.gpg}"
}
sign() { 
	_GnuPG --output "${1}.sig" $_pipe_pass --sign "$1"
	_status "${1}.sig"
}
clearsign() { 
	[[ "${1##*.}" != "${1%.*}" ]] && _output="${1%.*}.signed.${1##*.}" || _output="${1%.*}.signed"
	_GnuPG --output "$_output" $_pipe_pass --clearsign "$1"
	_status "$_output"
}
detach() { 
	_GnuPG --output "${1}.sig" $_pipe_pass --detach-sign "$1"
	_status "${1}.sig"	
} 
detached() { detach "$@" ; } # alias [actions validate per 'type' cmd]

# regular sig-file [$1] or detached sig-file [$1] & data-file [$2]
verify()  { _GnuPG $_pipe_pass --verify "$@" ; } 

revoke()  { # generate a revoke certificate; requires secret part of Primary key
	_GnuPG --output "${_keyFname}.revoke.asc" $_pipe_pass $_no_version --gen-revoke $_keyID 
	_status "${_keyFname}.revoke.asc"	
}
import() { # import pub|sec key [.asc, or whatever] into its pub|sec keyring 
	[[ -f "$@" ]] && { _GnuPG --import "$@" ; true; 
	} || errMSG "'$@' is NOT a file [key-file REQUIREd]" ; 
} 
export() { # secret|subkeys ; defaults to public key; encrypted per 'armor' [*.asc]
	[[ "$1" == 'subkeys' ]] && { _outfile="${_keyFname}.secret.subs.asc"; _keys=-secret-subkey; } 
	[[ "$1" == 'secret' ]]  && { _outfile="${_keyFname}.secret.asc"; _keys=-secret-keys; } 
	[[ ! "$1" ]]            && { _outfile="${_keyFname}.public.asc" ; _keys=; }
	# export selected key
	_GnuPG --output "$_outfile" --export$_keys --armor $_no_version $_keyID
	_status "$_outfile"
}
version() { _GnuPG --version; }
fpr() { _GnuPG --fingerprint $_keyID ; REQUIREs putclip ; putclip "$_fingerprint" ; printf "\n %s\n\n" "FINGERPRINT :: sent to clipboard" ; } ; fingerprint(){ fpr "$@" ; }
help()    { [[ ! "$1" ]] && { _GnuPG --help; } || { _GnuPG --help | fgrep "$1"; }	} 
edit()    { _GnuPG $_pipe_pass --edit-key $_keyID ; }
homedir() { printf "\n %s\n\n" "HOMEDIR :: $PWD"; ls -hlrtgGL --color=auto --time-style=+"%Y-%m-%d %H:%M" --group-directories-first ; keyringInfo ; }
dir() { homedir "$@" ; }
keyringInfo(){ printf "\n %s\n\n" "KEYRING :: $_email [$_keyFname]"; }
list() { # list pub|sec keys
	[[ "$1" == 'secret' ]] && { # list secret keys if $1
		_GnuPG --list-secret-keys $_keyID ; true;
	} || { # else list public keys
		_GnuPG --list-keys $_keyID ;
}	}
packets() { _GnuPG -a --export $_keyID | _GnuPG --list-packets --verbose ; } # ‘--debug 0x02’

arch() { # store [encrypted] arch of "$HOME/.gnupg" [keyrings etal] @ "$HOME/gpg/..."
	# $1 is optional description-str [$@]; appended to backup folder-name
	[[ "$1" ]] && { _path=" $@"; } || { _path=; } 
	_path="$HOME/gpg/[keyring backups]/${_keyFname} $( todaynow )${_path}"
	store "$_GPG_HOMEDIR" # create encrypted archive; "* [s].7z"
	mkdir "$_path" ; mv "$_GPG_HOMEDIR [s].7z" "${_path}/" # move arch to timestamped folder
	7z a "${_path}.zip" "${_path}" # zip then delete the folder; then inform
	[[ -d "$_path" && ( "$_path" != "${_path/'home/'$USERNAME}" ) ]] && rm -r "$_path"
	[[ -f "${_path}.zip" ]] && { clear; printf "\n %s\n" "ARCHIVEd :: keyring '${_path##*/}.zip' @ ~/gpg/[keyring backups]/" ; }
}
primary() {
	keyringInfo
	[[ ! "$_flag_sans_primary" ]] && { printf "\n %s\n" "... INCLUDES PRIMARY secret key"; } || { printf "\n %s\n" "... does NOT contain PRIMARY secret key"; }
}
pipe() { # show GLOBAL state [only]; can't ... 'source gpg pipe {ON|OFF}' ... WTF ???
	shopt -s nocasematch
	[[ "$1" == 'on' ]]  && export GPG_PIPE_PASS=1 # these don't work; see above
	[[ "$1" == 'off' ]] && export GPG_PIPE_PASS=
	[[ "$GPG_PIPE_PASS" ]] && echo "  pipe is ON [GPG_PIPE_PASS]" || echo "  NO pipe :: 'GPG_PIPE_PASS' is UNSET" ; 
}
strip() { # strip out the Primary key; save [.asc] and then remove all keys, then 
          # import subkey(s) only [sans Primary, 'SC', key] 	
	# option; remove passphrase from subkey(s); exports unencrypted; prompts for passphrase
	[[ "$1" ]] && { 
		[[ "$_flag_sans_primary" ]] || { errMSG "NOT ALLOWED [keyring does NOT contain Primary secret key]" ; return 0; } 
		_reset_pass='--export-options export-reset-subkey-passwd'
		_raw='.UNPROTECTED'
	} || unset _reset_pass
	# save (Primary) pub key & sec keys [encrypted]
	_GnuPG --output "${_keyFname}.secret.asc" --export-secret-keys --armor $_no_version $_keyID
	_status "${_keyFname}.secret.asc"
	_GnuPG --output "${_keyFname}.public.asc" --export --armor $_no_version $_keyID
	_status "${_keyFname}.public.asc"
	# save subkeys [unencrypted if $1 (passphrase removed); prompts for passphrase]
	_GnuPG --output "${_keyFname}.secret.subs${_raw}" $_pipe_pass --export-secret-subkeys $_reset_pass $_keyID
	_status "${_keyFname}.secret.subs${_raw}"
	# delete all keys on ring 
	_GnuPG --delete-secret-key $_keyID
	_GnuPG --delete-key $_UID
	# import subkeys only 
	_GnuPG --import "${_keyFname}.secret.subs${_raw}"
	printf "\n %s\n" 'IMPORTed [sans Primary] ...'
	_GnuPG --list-secret-keys $_keyID
	[[ "$_reset_pass" ]] && printf "\n %s\n" "$red PASSPHRASE was REMOVED $normal; secret subkey(s) exported $red UNPROTECTED $normal"
}
gen()  { # REF: https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html

	_pubring=pubring.gpg
	_secring=secring.gpg
	
	[[ "$1" == 'batch' ]] && {
	
		# -- batch mode [$1] :: 'dry-run' [default] or 'commit' per $2 --

		# debian https://keyring.debian.org/creating-key.html  [GnuPG 2.0.30 defaults]
		# the crypto-params-per-options method of config works @ GnuPG v 2.0.30, but fails @ GnuPG v 1.4 [w|w/out quotes]
		#_crypto_params='--personal-digest-preferences SHA256 --cert-digest-algo SHA256 --default-preference-list "SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed"'
		
		# inform [once] if keyring not empty
		[[ -f "$_GPG_HOMEDIR/cache" ]] || { 
			[[ "$_email" ]] && { printf "\n %s\n" "Keyring contains key of '$_email' [$_keyFname]"; }
		}
		# default params
		_name='Foo Bar'
		_email='foobar@baz.com'
		unset _comment
		[[ "$2" == 'commit' ]] && { 
			_mode='commit'  ; _GnuPG_agentX 
			(( $? )) && return 99 || true # end on agentX fail
		} || { 
			_mode='dry-run' ; _pass='---'
		}
		# get cached update if exist [from prior run]
		[[ -f "$_GPG_HOMEDIR/cache" ]] && {
			while IFS=';' read -a tokens || [[ -n "$tokens" ]]
			do
			   _name="${tokens[0]}" ; _email="${tokens[1]}" ; _comment="${tokens[2]}"
			done < "$_GPG_HOMEDIR/cache" ; true
		}
		# query user
		for param in _name _email _comment
		do 
			printf "\n %s" " ${param:1} [${!param}]: " ; read 
			[[ "$REPLY" ]] && { eval ${param}="'$REPLY'" ; } 
		done

		# 'Name-Comment:' param @ gen.params.txt ; remove param if value unset
		[[ "$_comment" ]] && _name_comment="Name-Comment: $_comment" || unset _name_comment

		# preserve 'gpg.conf' file; backup pre-existing [once] if exist
		[[ -f "$_GPG_HOMEDIR/gpg.conf" ]] && { [[ -f "$_GPG_HOMEDIR/gpg.conf.bak" ]] || { mv "$_GPG_HOMEDIR/gpg.conf" "$_GPG_HOMEDIR/gpg.conf.bak" ; } }

# (over)write params 'cache'
cat > "$_GPG_HOMEDIR/cache" <<EOF
$_name;$_email;$_comment
EOF

# (over)write 'gen.params.txt' file w/ latest from query|cache|default
cat > "$_GPG_HOMEDIR/gpg.params.txt" <<EOF
%echo gen-key per ${0##*/}
Key-Type: RSA
Key-Usage: sign
Key-Length: 4096
Subkey-Type: RSA
Subkey-Usage: encrypt
Subkey-Length: 4096
Name-Real: $_name
$_name_comment
Name-Email: $_email
Creation-Date: 2010-10-01
Expire-Date: 8y
Passphrase: $_pass
%$_mode
%pubring $_pubring
%secring $_secring
EOF

# (over)write 'gpg.conf' file w/ [debian.org suggested / GnuPG 2.0.30 default] preferences
cat > "$_GPG_HOMEDIR/gpg.conf" <<EOF
personal-digest-preferences SHA256
cert-digest-algo SHA256
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
EOF
		# generate key [inform if 'commit'] 
		[[ "$2" == 'commit' ]] && printf "\n %s\n\n" "$green Generating $normal keys ..."

		_GnuPG --batch $_crypto_params --gen-key "$_GPG_HOMEDIR/gpg.params.txt" ; _exit=$? ; true

	} || {

		# -- query mode [$1] --
		
		_GnuPG $_crypto_params $_pipe_pass --gen-key ; _exit=$? ; true		
		# --no-default-keyring --secret-keyring $_secring --keyring $_pubring --gen-key
		# ... use specified [pub/sec] keyrings; do not add them to list of keyrings 
	}
	# show status
	
	[[ ( "$2" == 'commit' ) || ( "$1" != 'batch' ) ]] && { 
		printf "\n %s\n\n" "GnuPG EXIT[$_exit]"
		_status "$_pubring" ; _status "$_secring" 
	} 
}

_status() { # reports on outfile success/fail 
	[[ -f "$@" ]] && { printf "\n %s\n" "$green SUCCESS $normal $_action :: '${@##*/}'" ; } || { errMSG "$_action @ $@" ; }	
}

_GnuPG() { gpg --no-permission-warning "$@" 2> /dev/null ; }

_GnuPG_agentX() {
	[[ "$_agentX" ]] || { errMSG "NO agentX set" ; return 99 ; }
	REQUIREs $_agentX ; (( $? )) && return 86 || true
	[[ "$_email" ]] && {
		[[ "$GPG_PIPE_PASS" ]] && {
			_pass=$( $_agentX -q "$_email" )
		} || {
			putclip $( $_agentX -q "$_email" )
		}
		_flag_agentX_call=1 ; return 0
	} || { errMSG "agentX [BAD PARAM]" ; return 99 ; }
}

# == INIT ==

REQUIREs push pop todaynow errMSG colors ; colors
# set homedir :: export GNUPGHOME=/cygdrive/s/test
#GNUPGHOME="$HOME/.gnupg"
_GPG_HOMEDIR="$GNUPGHOME"
[[ "$_GPG_HOMEDIR" ]] || _GPG_HOMEDIR="$HOME/.gnupg"
[[ -d "$_GPG_HOMEDIR" ]] || { errMSG "GnuPG HOMEDIR '$_GPG_HOMEDIR' NOT EXIST"; exit 99; }
#_homedir="--homedir '$_GPG_HOMEDIR'"
_no_version='--no-emit-version'
# show info if no params
[[ ! "$1" ]] && { script_info "$0" ; exit 0; } 
# run @ homedir [gpg keyring folder]

push "$_GPG_HOMEDIR" 

# use native if $1 begins w/ '-'
[[ "${1:0:1}" == '-' ]] && { gpg "$@"; exit 0; } 

# set action 
[[ "$1" ]] && _action="$1" || _action='list'
[[ "$(type -t $_action )" ]] || { errMSG "'$_action' is NOT a valid action"; exit 99; }

shift

# @ certain actions, get/set email per 2nd|3rd arg (before 'shift') if set
unset _email; unset _keyID
for action in edit fpr list primary 
do 
	[[ "$_action" == "$action" ]] && {
		[[ "$2" && "$1" == 'secret' ]] && _keyID="$2"
		[[ "$1" && "$1" != 'secret' ]] && _keyID="$1"
		[[ "$_keyID" ]] && { 
			_email="$( _GnuPG --list-secret-keys $_keyID | fgrep 'uid' )"
			[[ "$_email" ]] || _email="$( _GnuPG --list-keys $_keyID | fgrep 'uid' )"
	}	}
done
# if unset, get/set email-address per GPG_KEY [global] or gpg default
[[ "$_email" ]] || {
	_email="$( _GnuPG --list-secret-keys ${GPG_KEY// /} | fgrep 'uid' )"
	[[ "$_email" ]] || _email="$( _GnuPG --list-keys ${GPG_KEY// /} | fgrep 'uid' )"
}
_email="${_email#*<}"
_email="${_email%>*}"

# set UID per email
_UID="${_email%@*}"
[[ "$_UID" ]] || errMSG "NO UID"

# get/set keyID per UID
_fingerprint="$( _GnuPG --fingerprint $_UID | fgrep 'fingerprint' )"
_fingerprint="${_fingerprint##*=}"
_fingerprint="${_fingerprint# }" # 10x4-chars + whitespaces
_keyID="${_fingerprint// /}"     # 40-char (160 bits)
_keyFname="${_keyID:(-8)}"       #  8-char ( 32 bits)
[[ "$_keyID" ]] || errMSG "NO keyID"

# @ certain actions, test for Primary key [secret part]; sec|sec#
for action in primary revoke export strip arch dir homedir
do 
[[ "$_action" == "$action" ]] && { 
	_flag_sans_primary=1
	[[ "$( _GnuPG --list-secret-keys $_keyID | fgrep 'sec ' )" ]] && unset _flag_sans_primary
}
done
# append '-sans' to keyFname if keyring does NOT contain Primary [SC] key
[[ "$_flag_sans_primary" ]] && _keyFname="$_keyFname-sans"

# @ certain actions, forbid if sans Primary key
[[ "$_flag_sans_primary" ]] && {
	for action in revoke strip
	do 
	[[ "$_action" == "$action" ]] && { 
		errMSG "NOT ALLOWED [keyring does NOT contain Primary secret key]" ; exit 99;
	}
	done
}
# @ certain actions, pipe passphrase if GPG_PIPE_PASS set; always if $@ = 'gen batch'
unset _pipe_pass
for action in decrypt sign clearsign detach detached verify edit revoke strip
do # @ all listed actions except 'strip' without its option ['raw']
	[[ "$_action" == "$action" ]] && { [[ "$_action" == 'strip' && ! "$1" ]] || {
		_GnuPG_agentX
		[[ "$GPG_PIPE_PASS" ]] && { # pipe it & inform if gpg-pipe-pass set
			printf "\n %s%s%s\n\n" 'PIPE PASSphrase ==> GnuPG('$_action') ...'
			_pipe_pass='--passphrase-fd 0'
	} }	}
done

# @ certain actions, unset keyID if not specified; process all keys --
for action in list
do 
[[ ( "$_action" == "$action" ) && ! "$GPG_KEY" && ( ! "$1" || ( "$1" == 'secret' ) ) ]] && unset _keyID
done

# == DO ==

echo # show homedir path if action not 'list'
[[ "$_action" == 'list' ]] || {
	printf "%s\n" "$_GPG_HOMEDIR"
	echo '------------------------------------------------------'
}

# call action ( pipe if pipe-pass set )
[[ "$_pipe_pass" ]] && { printf "$_pass" | $_action "$@"; true ; } || { $_action "$@"; }
pop

# cleanup
[[ "$_flag_agentX_call" ]] && { 
	_pass="# PID:$$ PWD:'$PWD' PATH:'$PATH'"
	[[ "$GPG_PIPE_PASS" ]] || { putclip $_pass ; putclip ; }
	unset _pass
}
