#!/usr/bin/env bash
#------------------------------------------------------------------------------
# A `go run .` equivalent; a `go build ...` wrapper featuring ...
#   - Leaves no residue folder(s) @ TEMP, e.g., /go-build*/
#   - Limits MS Firewall pop-up to ONCE per DIR (vs infinitely otherwise).
#   - Auto deletes the binary (./goRun) on kill (CTRL+C)  ** BUGGY **
#
#  >>>  RUN AS SOURCE  <<<
# 
# $ . gorun
# -----------------------------------------------------------------------------
[[ $_ == $0 ]] && { printf "\n  %s\n" "Run as SOURCE."; exit; }

# Delete old build folders
find "/c/Users/${USER^^}/AppData/Local/Temp" -mmin +10 -type d \
    -name 'go-build*' -exec rm -rf {} \+ & 
# Delete old goRun files under PWD
find . -name 'goRun' -exec rm "{}" \+ &
clear

export _task='goRun'

cleanup_gorun(){
    [[ "$OSTYPE" != 'linux-gnu' ]] && exit
    # Delete binary after task dies (tail terminates); wait for task to start.
    sleep 1 && tail --pid=$( pidof $_task ) -f /dev/null && rm ./$_task && clear
}

cleanup_gorun & 
go build -o $_task && ./$_task "$@"

exit
# =====================================

# Author @ https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash 
export _task='goRun'

_term() { 
  echo "Caught SIGTERM signal!" 
  #kill -TERM "$child" 2>/dev/null
  
  rm ./$_task & clear
}

trap _term SIGTERM

go build -o $_task && ./$_task &

child=$! 
wait "$child"
