#!/bin/bash
# -----------------------------------------------------------------------------
# Download [wget] and clean hosts file, per URL, to stdout.
# 
# ARGs: all | each | <url> [<any{for-HTTP-Headers-only}>]
# 
# REF: https://github.com/StevenBlack/hosts
#      https://hosts-file.net/
# 
#  SteveBlack :: "Unified hosts = (adware + malware)"
#    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
#  MitchellKrogZA :: Bad-Boyz-Hosts
#    https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
#  MitchellKrogZA :: Ultimate Hosts Blacklist [40 MB]
#    https://hosts.ubuntu101.co.za/hosts
# 
#  hpHosts :: ad_servers  (all|each) 
#    https://hosts-file.net/ad_servers.txt 
#    >>>  DEAD LINK @ 2020-04 (hpHosts terminated the project.)  <<<
# -----------------------------------------------------------------------------
REQUIREs wget ; (( $? )) && exit 86
[[ "$1" ]] || { script_info "$0"; exit 99; }
[[ "$1" == 'all' ]] && {
    # all to stdout, each per recursive call
	# for file in ad_servers exp emd hjk grm psh
	# do 
	# 	${0##*/} https://hosts-file.net/${file}.txt # DEAD LINK @ 2020-04 (hpHosts terminated the project.)
	# done
    ${0##*/} https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    #${0##*/} https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
	
	exit
}
[[ "$1" == 'each' ]] && {
	# for file in ad_servers exp emd hjk grm psh
	# do # each to hosts.$file, per recursive call
	# 	${0##*/} https://hosts-file.net/${file}.txt > hosts.${file}
	# done
    echo 'NOPE :: hpHosts terminated the project @ 2020-04.'
	
	exit
}
[[ "$2" ]] && { 
	# HTTP-Headers-only; to stdout
	# https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Response_fields
	wget -t 1 -S --spider -O - "$1" 2>&1 
} || {
  # Print content to stdout; sort/unique; remove: loopback-only entries,
  # empty lines, and lines starting with '#', SPACE or TAB;
  # replace all '127.0.0.1' with '0.0.0.0' .
  wget -q -t 1 -S -O - "$1" \
    | grep -iv '^ ' \
    | sed -re '/^\s*$/d' \
    | awk '{print $1 " " $2}' \
    | grep -iv '^#' \
    | sed 's/127.0.0.1/0.0.0.0/' \
    | fgrep -iwv '0.0.0.0 0.0.0.0' \
    | fgrep -iwv '0.0.0.0 localhost' \
    | fgrep -iwv '::1 localhost' \
    | fgrep -iwv '::1 ip6-localhost' \
    | fgrep -iwv '::1 ip6-loopback' \
    | fgrep -iwv '0.0.0.0 local' \
    | fgrep -iwv '::1 local' \
    | fgrep -iv 'fe80::' \
    | fgrep -iv 'ff00::' \
    | fgrep -iv 'ff02::' \
    | fgrep -iwv '255.255.255.255 broadcasthost' \
    | fgrep -iwv 'Binary file' \
    | sort -u
}


#echo "ERR[$?]"
#(( $? )) && errMSG "BAD URL @ '$1'"
