#!/usr/bin/env bash
# -----------------------------
#  kubectl wrapper 
# -----------------------------
_minik() {
    [[ "$OSTYPE" != 'linux-gnu' ]] && {
        [[ "$1" == 'quick' || "$1" == 'cleanup' ]] && {
            printf "\n  %s\n" 'REQUIREs linux-gnu platform'; return
        }
    }
    case $1 in
        "config") # print
            cat ~/.kube/config
        ;;
        "unix" | "bash") # Unix paths
            cp ~/.kube/config.Unix ~/.kube/config
            tail -n 2 ~/.kube/config
        ;;
        "win") # Win paths
            cp ~/.kube/config.Win ~/.kube/config
            tail -n 2 ~/.kube/config
        ;;
        "quick") # Deploy hello-minikube
            kubectl run hello-minikube \
              --image=k8s.gcr.io/echoserver:1.4 \
              --port=8080 && \
            kubectl expose deployment 'hello-minikube' \
              --type=NodePort && \
            kubectl get service ; true
        ;;
        "cleanup") # Delete all deployments & services
            kubectl delete services --all
            kubectl delete deployment --all
        ;;
        *) # Instruct
            printf "\n  %s\n" 'config | unix | win | quick | cleanup'
        ;;
    esac
}

_minik "$@"

exit 

# Hello Minikube :: [Quickstart](https://kubernetes.io/docs/setup/minikube/#quickstart) (@ bash | PowerShell)

# Start cluster 
minikube start
# Apply deployment; a pod exposed to port 8080
kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.4 --port=8080 
# Expose an endpoint per NodePort
kubectl expose deployment hello-minikube --type=NodePort
# Get status (multiple times) as pod is created/configured
kubectl get pods
# Get public IP:PORT
minikube service hello-minikube --url
# Request/Response from HTTP server, per curl ...
curl $(minikube service hello-minikube --url)

# Cleanup
kubectl delete services hello-minikube
kubectl delete deployment hello-minikube
# Turn off the Minikube; the cluster's VM
minikube ssh     # into VM
$ sudo poweroff  # from inside VM

