#!/bin/bash

_openedit() {(
    # ARGs: PATH | FNAME(searches @ configured scripts paths)
    # opens $@ in _EDITOR, which may be preset else default
    REQUIREs errMSG ; unset _flag
    
    # DEFINE
    # ======
    handler() {
        if [[ -f "$@" ]]
        then 
            if [ "$( type -t notepad.exe )" ]
            then  # set editor per preset else first found
            # @ Windows (WSL|MINGW64|Cygwin)
                [[ "$_EDITOR" ]] || { 
                    [[ "$( type -t code )" ]] && _EDITOR='code -r'
                    [[ "$_EDITOR" ]] || _EDITOR='notepad.exe'
                }
                # if vim is only editor 
                [[ "$_EDITOR" == 'vim' ]] && { vim "$@"; return 0; }
                # @ WSL|MINGW64 (Git-for-Windows)
                [[ "$OSTYPE" != 'cygwin' ]] && { 
                    $_EDITOR "$( cygpath -aw "$@" )" # if "$@", then WSL (now) prepends bogus root
                } || { # @ cygwin, subshell/bkgnd handles range of issues per editor
                    ( $_EDITOR "$( cygpath -aw "$@" )" > /dev/null 2>&1 ) & 
                }
            else
            # @ Linux, vim else vi
                [[ $( type -t '/usr/bin/vim' ) ]] && _vi=vim || _vi=vi
                $_vi "$@"
            fi 
        else  
                errMSG "'$1' NOT FOUND" 
        fi
        _flag=1
    }  
    
    # EXECUTE 
    # =======
    # try exact match, else try ...
    [[ -f "$1" ]] && { handler "$1"; true; } || { 
    
        # @ bash-scripts folder, try $1
        _tryA="${_SCRIPTS_FOLDER}/${1##*/}"
        _tryB="${_PRJ_HOME}/${1##*/}"
        _tryC="${_PRJ_HOME}/.bin/${1##*/}"
        [[ -f "$_tryA" ]] && handler "$_tryA"
        [[ -f "$_tryB" ]] && handler "$_tryB"
        [[ -f "$_tryC" ]] && handler "$_tryC"
        
        # @ cmd-library folder, try $1 and _$1
        _tryA="${_UNREG_FOLDER}/cmd_library/${1##*/}"
        _tryB="${_UNREG_FOLDER}/cmd_library/_${1##*/}"
        [[ -f "$_tryA" ]] && handler "$_tryA"
        [[ -f "$_tryB" ]] && handler "$_tryB"
        
        # @ cmd-library folder, try appending '.bat', if all else failed
        [[ ! "$_flag" ]] && { 
            [[ -f "${_tryA}.bat" ]] && handler "${_tryA}.bat"
            [[ -f "${_tryB}.bat" ]] && handler "${_tryB}.bat"
        }
    }
)}

_openedit "$@"
