#!/bin/bash
# --------------------------------------------------------------------- 
#  Convert jpg to png file or all @ folder
# --------------------------------------------------------------------- 
[[ $( printf %s "$PATH" | grep -i 'FFmpeg/bin' ) ]] || source ffmpeg 

[[ -f "$@" ]] && ffmpeg.exe -i "$@" "${@%.*}.png" -y -hide_banner
[[ -d "$@" ]] && find "$@" -type f -iname '*.jpg' -exec /bin/bash -c 'png "$@" &' _ {} \; 

# [[ -d "$@" ]] && png.bat "$( cygpath -w "$@" )"

