#!/bin/sh
# ------------------------------------------------------
#  urandom alpha-num string of length $1
# ------------------------------------------------------
exit
[[ $1 ]] && { cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $1 | head -n 1 }

