#!/usr/bin/env bash
# -------------------------------------------------------------
#  siterip :: Download an entire [Tor] website.  
#  
#  ARGs: URL [tor]
#  
#  E.g. foo.com/bar/  (limits to /bar and below)
# -------------------------------------------------------------
[[ "$1" ]] || { script_info "$0"; exit 99; }
[[ $(type -t wget) ]] || exit 99; unset _tor; _URL=$1; 
_DOMAIN="${_URL/\/*/}"
[[ "$2" == 'tor' ]] && { _tor='torsocks'; [[ $(type -t $_tor) ]] || exit 99; }

${_tor} wget \
    --recursive \
    --no-clobber \
    --page-requisites \
    --html-extension \
    --convert-links \
    --restrict-file-names=windows \
    --domains $_DOMAIN \
    --no-parent \
    $_URL
