#!/usr/bin/env bash
# -------------------------------------------------------------
#  Convert indentation from two to FOUR SPACES
#  
#  ARGs: FILE
# -------------------------------------------------------------
[[ -f "$@" ]] || { script_info "$0"; exit 99; }

sed -e 's/^/~/' -e ': r' -e 's/^\( *\)~  /\1    ~/' -e 't r' -e 's/~//' "$@"