#!/usr/bin/env bash

_storeroot() {
    # PARAMs: [OSTYPE] ; defaults to current platform per $OSTYPE
    # Create and store certain root files and folders to their per-platform store 
    # @ ~/etc/platforms/<OSTYPE>/HOME. 
    REQUIREs timestamp; (( $? )) && return 86; echo "@ $FUNCNAME"
    _HOME=${HOME}
    [[ $_HOME ]] || _HOME=~
    _store="$( _store_per_platform $1 )" ; (( $? )) && return 99
    _tgz() { # PARAMs: <piped>
        export _store 
        # create archive at store if source is newer; set archive mtime to that of source
        xargs -I {} bash -c '[[ "$@" -nt "${_store}/${@##*/}.tgz" ]] && { echo "  ${@##*/}"; /bin/tar -caf "${_store}/${@##*/}.tgz" --exclude=.aws/shell/* --exclude=.config/Code/* --exclude=.config/chromium-* --exclude=*/node_modules/* -C "$_HOME" "${@##*/}"; [[ -f "${_store}/${@##*/}.tgz" ]] && touch -r "$@" "${_store}/${@##*/}.tgz"; }' _ "{}" 
    }
    find "$_HOME" -maxdepth 1 -type f -iname '.*.tgz' -exec rm "{}" \;
    
    #timestamp "$_HOME" 1 #> /dev/null 2>&1 # update folder mtimes 
    # archive certain HOME dot-files (find w/ exclusions)

    #echo "$_HOME";echo "$@";return

    find "$_HOME" -maxdepth 1 -type f \( \
        -name '.*' \
        ! -name '.rnd' \
        ! -name '*.7z' \
        ! -name '*.zip' \
        ! -name '*.tgz' \
        ! -name '*.txz' \
        ! -name '.*history' \
        ! -name '.*hst*' \
        ! -iname '.x*' \
        ! -iname '.server*' \
        ! -iname '.viminfo' \
        \) -print | _tgz
    # archive certain HOME dot-files (find w/ or)
    find "$_HOME" -maxdepth 1 -type f \( \
        -name '*.bat' \
        -or -name '*.cmd' \
        -or -name '*.sh' \
        -or -name '*.conf' \
        \) -print | _tgz
    # archive certain HOME dot-folders
    for d in aws ssh passgo config ; do { 
        [[ -d "$_HOME/.$d" ]] && { echo "$_HOME/.$d" | _tgz ; } 
    } done
    # archive docker.prj folder
    echo "$_HOME/docker.prj" | _tgz 
    
    tgz "$_HOME/.docker/config.json" 
    mv "$_HOME/.docker/config.json.tgz" "${_store}/"
    #| _tgz
    # move .*.tgz to the store 
    for file in "$_HOME/."*; do [[ "${file##*.}" == 'tgz' ]] && mv $file "$_store/" ; done

    return 
}

_storeroot "$@"