#!/usr/bin/env bash

# -- backup/synch --

_synch() { 
    # PARAMs: NAME | SOURCE TARGET
    REQUIREs errMSG rsync; (( $? )) && return 86;unset _err
    
    # rsynch wrapper; creates target dir, if needed, if target parent exist
    # handles rsync source-slash weirdness; appends slash if none, if dir
    _rsync() {
        printf "\n %s\n" "SOURCE:  '${1}'"
        printf " %s\n\n" "TARGET:  '${2}'"
        _source="${1}"
        [[ -d "${1}" ]] && { [[ "${1:(-1)}" != '/' ]] && _source="${1}/"; } 
        [[ -e "$_source" ]] || { errMSG 'source does NOT EXIST'; return 99; }
        rsync -irtu --delete --exclude='/REFs' --exclude='*~' --exclude='*.swp' --include='.*' "$_source" "$2" 
    }
    
    [[ ! "$@" ]] && _err=99 || { 
        # @ SOURCE TARGET, update with purge
        [[ -e "$1" && -e "${2%/*}" ]] && { 
            _rsync "$1" "$2"
        } || { 
        # @ NAME, synchronize its scripted source[s]/target[s]
            case ${1^^} in 
                'SMB' | 'STAGING') 
                { # /home/$USERNAME/etc <==> STAGING 
                    [[ -d "${_STAGING_FOLDER}" ]] || { errMSG '_STAGING_FOLDER does NOT EXIST'; return 86; }
                    [[ ! "$2" || "${2,,}" == 'push' ]] && { # push => STAGING
                        printf "\n %s\n" 'SYNCH [push]' 
                        archive home # first update home archive if stale
                        _rsync "$_HOME/etc/" "${_STAGING_FOLDER}/etc/" # /etc => STAGING
                        [[ -d "$_STAGING_FOLDER/scratch" ]] || { errMSG 'scratch folder does NOT EXIST'; return 86; }
                        _tgz=$( newest "$_ETC_ARCHIVES_FOLDER")  # $USER.etc.YYYY-MM-DD_[HH.MM.SS].tgz
                        _rsync "$_tgz" "$_STAGING_FOLDER/scratch/${_tgz##*/}" # tgz => STAGING
                    }
                    [[ "${2,,}" == 'pull' ]] && { # pull <= STAGING
                        printf "\n %s\n" 'SYNCH [pull]' 
                        _rsync "${_STAGING_FOLDER}/etc" "$_HOME/etc/" # /etc <= STAGING
                    }
                } ;;
                 'REFS')    refsync ${2-push} ;;
                'ALLREFS')  refsync ${2-push} ;;

                # rclone wrapper 
                "install") curl https://rclone.org/install.sh | sudo bash ;;
                "config") rclone config ;;
                "DROPBOX") 
                {
                    _exclude='--exclude desktop.ini'
                    echo '@ Dropbox/disk_utilities'
                    _SRC='/d/Dropbox/disk_utilities'  
                    _REMOTE='dropbox'  
                    _DST='disk_utilities'  
                    rclone sync $_SRC $_REMOTE:$_DST -v -c $_exclude
                    echo '@ Dropbox/store'
                    _SRC='/d/Dropbox/store'  
                    _DST='store'  
                    rclone sync $_SRC $_REMOTE:$_DST -v -c $_exclude

                } ;; 
                "GOOGLE" | "MEGA") 
                {
                    _exclude='--exclude desktop.ini'
                    echo '@ Dropbox/disk_utilities'
                    _SRC='/d/Dropbox/disk_utilities' 
                    _REMOTE="${1,,}"
                    _DST='Dropbox/disk_utilities'  
                    rclone sync $_SRC $_REMOTE:$_DST -v -c $_exclude
                    echo '@ Dropbox/store'
                    _SRC='/d/Dropbox/store' 
                    _DST='Dropbox/store'  
                    rclone sync $_SRC $_REMOTE:$_DST -v -c $_exclude
                    echo '@ Dropbox/storage'
                    _SRC='/d/Dropbox/storage' 
                    _DST='Dropbox/storage'  
                    rclone sync $_SRC $_REMOTE:$_DST -v -c $_exclude
                } ;;
                *) _err=99 ;;
            esac
    }  }
    [[ "$_err" ]] && { errMSG 'REQUIREs source and target paths, or configured NAME'; return $_err; }

    return 0
}

_synch "$@"