#!/bin/bash
# -----------------------------------------------------------------
# WoL :: Send Magic Packet to host[s] on LAN per NetCat [nc]
# https://stackoverflow.com/questions/31588035/bash-one-line-command-to-send-wake-on-lan-magic-packet-without-specific-tool
# SOLUTION from user 'Sopalajo de Arrierez' @ StackOverflow.com:
# 
#  The WOL magic packet is composed of ffffffffffff (12 times f) 
#  followed by 16 times the destination MAC without colons (:).
# 
#  The sed command is used here to remove colons (:) from 
#  the MAC and to add the '\x' hex specificator 
#  ('11' becomes '\x11' and so on) prior to sending 
#  the string to the network stack.
# 
#  The forged wake-on-LAN package is sent to the network stack 
#  piping it to NetCat. SoCat can be used instead 
#  (syntax will differ, of course).
#
#  Tested working on Ubuntu, Kali and 
#  even CygWin (Windows 7 SP 1 64 bits).
# -----------------------------------------------------------------
WoL() {
	_Broadcast='255.255.255.255'
	_PortNumber='4000'  # works, but WoL is port 9 purportedly
	_targets="D0:50:99:1C:BC:27 70:85:C2:3B:C6:54"  # HTPC XPC

	for MAC in $_targets 
	do 
		# WoL per NetCat @ Linux||Cygwin
		[[ "$OSTYPE" != 'cygwin' ]] && _b='-b' || unset _b 
		echo -e $(echo $(printf 'f%.0s' {1..12}; printf "$(echo $MAC | sed 's/://g')%.0s" {1..16}) | sed -e 's/../\\x&/g') | nc -w1 -u $_b $_Broadcast $_PortNumber
	done
}

WoL

exit
