#!/usr/bin/env bash
# -------------------------------------------------------------
#  cURL wttr.in :: local weather + 3-day forecast
# 
#  ARGs: [lo ca tion] (defaults to local)
# -------------------------------------------------------------
[[ "$( type -t curl )" ]] || { script_info "$0"; exit 99; }

[[ ! "$@" ]] && curl -s wttr.in || { 
    curl -s wttr.in/$(printf "%s " "$@" \
        | awk -F ' ' '{ s = ""; for (i = 1; i <= NF; i++) s = s $i "+"; print s }' \
        | sed 's/.$//') #... makes 'salt+lake+city' from 'salt lake city'.
}
exit 

# Firefox
-A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0'
# Chrome
-A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'
