---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lab4
spec:
  # StorageClass not required for manual PV/PVC/Pod config.
  storageClassName: bogus
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
