kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim
spec:
  # Bogus StorageClass : Used here as Label (See pv.yaml)
  storageClassName: demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
