apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-pods
  namespace: default
rules:
  # Authorization to list other Pods
  - apiGroups:
    - ''
    resources:
    - pods
    verbs:
    - list
