apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: new
    type: canary
  name: new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: new
        type: canary
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
        volumeMounts:
          - name: cm-vol
            #mountPath: /usr/share/nginx/html/index.html
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: cm-vol
          configMap:
            name: canary
status: {}
