apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: old
    type: canary
  name: old
spec:
  replicas: 3
  selector:
    matchLabels:
      app: old
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: old
        type: canary
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        resources: {}
status: {}
