## Multi-container Pod : Sidecar pattern
kind: Pod
apiVersion: v1
metadata:
  name: sidecar-pod
spec:
  ## Shared volume
  volumes:
  - name: logs
    emptyDir: {}

  containers:

  ## Main container
  - name: app
    image: busybox
    command: ["/bin/sh"]
    ## Main app process
    args: ["-c", "while true; do date >> /var/log/date.txt; sleep 10;done"]
    volumeMounts:
    - name: logs
      mountPath: /var/log

  ## Sidcar container
  - name: sidecar
    image: centos/httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logs
      mountPath: /var/www/html