# https://docs.docker.com/compose/compose-file
version: '3.8'

x-logopts:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields 
    &default-logopts  # https://docs.docker.com/compose/compose-file/compose-file-v3/#logging 
    options:
        max-size: "12m"
        max-file: "5"
    driver: json-file

networks:
    pvt1:
        driver: overlay
        external: true

secrets:
    pg_pw_postgres:
        external: true
    pg_pw_replicator:
        external: true
    pg_pw_app_owner:
        external: true
    pg_pw_app_user:
        external: true

configs:
    postgresql_src_conf:
        file: ${PATH_ABS_PGHA_CONFIG}/postgresql.src.conf

x-svc: &default-svc
        image: ${PGHA_IMAGE}
        user: "70:70"
        networks:
            pvt1:
        ports:
            - 5432
        configs:
            - source: postgresql_src_conf
              target: /postgresql_src_conf
              uid: "70"
              gid: "70"
              mode: 0660
        secrets:
            - pg_pw_postgres
            - pg_pw_replicator
            - pg_pw_app_owner
            - pg_pw_app_user
        env_file:
            - ${PATH_ABS_HOST_ASSETS}/.env/pgha.env
        environment:
            - APP_DB_PASSWORD_FILE=/run/secrets/pg_pw_app_user
        command: ["postgres", "-c", "config_file=/postgresql_src_conf"]
        logging: *default-logopts

services:

    ############################################
    ###  @ First run : db init 
    ###  or other admin (loads Docker secrets)
    ############################################

    pg1: 
        <<: *default-svc
        hostname: "${PGHA_HOST1}"
        volumes: # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
            - ${PATH_ABS_VM_STORE}/pgha/pgdata:${PATH_ABS_CTNR_PGDATA}
            - ${PATH_ABS_VM_STORE}/pgha/archive:${PATH_ABS_CTNR_PGARCHIVE}
            - ${PATH_ABS_VM_STORE}/pgha/etc:${PATH_ABS_CTNR_PG_ETC}
            - ${PATH_ABS_VM_STORE}/pgha/sql:${PATH_ABS_CTNR_PG_SQL}
            #- ${PATH_ABS_VM_ASSETS}/sql:${PATH_ABS_CTNR_PGHOME}/sql
        command: ["sleep", "1d"] #... override; start ctnr sans postgres server.
        deploy: # https://docs.docker.com/compose/compose-file/compose-file-v3/#deploy 
            replicas: 1
            placement:
                constraints: 
                    - node.labels.pg1 == true

    pg2: 
        <<: *default-svc
        hostname: "${PGHA_HOST2}"
        volumes:
            - ${PATH_ABS_VM_STORE}/pgha/pgdata:${PATH_ABS_CTNR_PGDATA}
            - ${PATH_ABS_VM_STORE}/pgha/archive:${PATH_ABS_CTNR_PGARCHIVE}
            - ${PATH_ABS_VM_STORE}/pgha/etc:${PATH_ABS_CTNR_PG_ETC}
            - ${PATH_ABS_VM_STORE}/pgha/sql:${PATH_ABS_CTNR_PG_SQL}
            #- ${PATH_ABS_VM_ASSETS}/sql:${PATH_ABS_CTNR_PGHOME}/sql
        #command: ["sleep", "1d"] #... override; start ctnr sans postgres server.
        deploy: # https://docs.docker.com/compose/compose-file/compose-file-v3/#deploy 
            replicas: 1
            placement:
                constraints: 
                    - node.labels.pg2 == true